import { db, type Recipe } from './index'

const seedRecipes: Omit<Recipe, 'id'>[] = [
  {
    name: 'Ayam Goreng Bumbu Kuning',
    emoji: '🍗',
    category: 'Protein',
    waktuMasak: 30,
    level: 'Mudah',
    porsi: 4,
    bahan: [
      { nama: 'Ayam', jumlah: '1 ekor, potong 8', kategori: 'Protein' },
      { nama: 'Kunyit', jumlah: '3 cm', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '5 siung', kategori: 'Bumbu' },
      { nama: 'Ketumbar bubuk', jumlah: '1 sdt', kategori: 'Bumbu' },
      { nama: 'Garam', jumlah: 'secukupnya', kategori: 'Bumbu' },
      { nama: 'Minyak goreng', jumlah: 'secukupnya', kategori: 'Stok' },
    ],
    langkah: [
      'Haluskan kunyit, bawang putih, ketumbar, dan garam',
      'Lumuri ayam dengan bumbu halus, diamkan 30 menit (atau semalam di kulkas)',
      'Rebus ayam berbumbu dengan sedikit air hingga bumbu meresap dan air habis',
      'Goreng ayam hingga kuning keemasan',
    ],
    tipsPrep: 'Marinasi semalam di kulkas untuk rasa lebih meresap. Bisa dibekukan setelah direbus.',
    tahanSimpan: 'Kulkas 3 hari, freezer 2 minggu (sebelum digoreng)',
    isFavorite: false,
  },
  {
    name: 'Tumis Kangkung Terasi',
    emoji: '🥬',
    category: 'Sayur',
    waktuMasak: 15,
    level: 'Mudah',
    porsi: 3,
    bahan: [
      { nama: 'Kangkung', jumlah: '2 ikat', kategori: 'Sayur' },
      { nama: 'Bawang merah', jumlah: '5 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '3 siung', kategori: 'Bumbu' },
      { nama: 'Cabai merah', jumlah: '5 buah', kategori: 'Bumbu' },
      { nama: 'Terasi', jumlah: '1 sdt', kategori: 'Bumbu' },
      { nama: 'Gula, garam', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Siangi kangkung, potong-potong, cuci bersih',
      'Iris bawang merah, bawang putih, dan cabai',
      'Tumis bumbu iris hingga harum, tambahkan terasi, aduk',
      'Masukkan kangkung, aduk cepat dengan api besar hingga layu',
      'Tambahkan gula dan garam, aduk rata, angkat',
    ],
    tipsPrep: 'Kangkung bisa disiangi dan dicuci sehari sebelumnya, simpan di wadah tertutup dengan tisu basah.',
    tahanSimpan: 'Sebaiknya langsung dimakan. Kulkas max 1 hari.',
    isFavorite: false,
  },
  {
    name: 'Telur Balado',
    emoji: '🥚',
    category: 'Protein',
    waktuMasak: 20,
    level: 'Mudah',
    porsi: 4,
    bahan: [
      { nama: 'Telur', jumlah: '8 butir', kategori: 'Protein' },
      { nama: 'Cabai merah keriting', jumlah: '10 buah', kategori: 'Bumbu' },
      { nama: 'Cabai rawit', jumlah: '5 buah', kategori: 'Bumbu' },
      { nama: 'Bawang merah', jumlah: '8 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '3 siung', kategori: 'Bumbu' },
      { nama: 'Tomat', jumlah: '2 buah', kategori: 'Sayur' },
      { nama: 'Gula, garam, kaldu', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Rebus telur, kupas, goreng sebentar hingga berkulit',
      'Haluskan cabai, bawang merah, bawang putih, dan tomat',
      'Tumis bumbu halus hingga matang dan minyak pecah',
      'Masukkan telur goreng, aduk hingga bumbu merata',
      'Tambahkan gula, garam, dan kaldu. Masak 2 menit.',
    ],
    tipsPrep: 'Telur bisa direbus dan dikupas sehari sebelumnya. Bumbu halus bisa dibekukan.',
    tahanSimpan: 'Kulkas 3 hari',
    isFavorite: false,
  },
  {
    name: 'Tempe Bacem',
    emoji: '🫘',
    category: 'Protein',
    waktuMasak: 45,
    level: 'Sedang',
    porsi: 4,
    bahan: [
      { nama: 'Tempe', jumlah: '3 papan', kategori: 'Protein' },
      { nama: 'Gula merah', jumlah: '100g, sisir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '5 siung', kategori: 'Bumbu' },
      { nama: 'Ketumbar', jumlah: '1 sdm', kategori: 'Bumbu' },
      { nama: 'Daun salam', jumlah: '3 lembar', kategori: 'Bumbu' },
      { nama: 'Lengkuas', jumlah: '3 cm, geprek', kategori: 'Bumbu' },
      { nama: 'Kecap manis', jumlah: '3 sdm', kategori: 'Stok' },
      { nama: 'Air asam jawa', jumlah: '2 sdm', kategori: 'Bumbu' },
    ],
    langkah: [
      'Potong tempe sesuai selera',
      'Haluskan bawang putih dan ketumbar',
      'Rebus tempe dengan bumbu halus, gula merah, kecap, air asam, daun salam, dan lengkuas',
      'Masak hingga air menyusut dan bumbu meresap',
      'Bisa langsung dimakan atau digoreng untuk tekstur renyah',
    ],
    tipsPrep: 'Makin lama direndam bumbu, makin enak. Bisa diprep 2 hari sebelumnya.',
    tahanSimpan: 'Kulkas 4-5 hari (justru makin enak!), freezer 2 minggu',
    isFavorite: false,
  },
  {
    name: 'Sayur Asem',
    emoji: '🍲',
    category: 'Sayur',
    waktuMasak: 40,
    level: 'Sedang',
    porsi: 5,
    bahan: [
      { nama: 'Jagung manis', jumlah: '2 buah, potong', kategori: 'Sayur' },
      { nama: 'Labu siam', jumlah: '1 buah', kategori: 'Sayur' },
      { nama: 'Kacang panjang', jumlah: '10 batang', kategori: 'Sayur' },
      { nama: 'Melinjo', jumlah: '50g', kategori: 'Sayur' },
      { nama: 'Asam jawa', jumlah: '2 sdm', kategori: 'Bumbu' },
      { nama: 'Cabai hijau', jumlah: '5 buah', kategori: 'Bumbu' },
      { nama: 'Bawang merah', jumlah: '5 butir', kategori: 'Bumbu' },
      { nama: 'Gula merah', jumlah: '50g', kategori: 'Bumbu' },
      { nama: 'Garam', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Rebus air, masukkan jagung dan melinjo (butuh waktu lebih lama)',
      'Haluskan bawang merah, cabai hijau',
      'Setelah jagung setengah matang, masukkan labu siam dan bumbu halus',
      'Tambahkan air asam jawa, gula merah, dan garam',
      'Masukkan kacang panjang terakhir, masak 5 menit, angkat',
    ],
    tipsPrep: 'Sayuran bisa dipotong sehari sebelumnya. Simpan terpisah di wadah.',
    tahanSimpan: 'Kulkas 2-3 hari',
    isFavorite: false,
  },
  {
    name: 'Nasi Goreng Spesial',
    emoji: '🍳',
    category: 'Karbohidrat',
    waktuMasak: 20,
    level: 'Mudah',
    porsi: 2,
    bahan: [
      { nama: 'Nasi dingin', jumlah: '2 piring', kategori: 'Karbohidrat' },
      { nama: 'Telur', jumlah: '2 butir', kategori: 'Protein' },
      { nama: 'Bawang merah', jumlah: '4 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '2 siung', kategori: 'Bumbu' },
      { nama: 'Cabai rawit', jumlah: '3 buah', kategori: 'Bumbu' },
      { nama: 'Kecap manis', jumlah: '2 sdm', kategori: 'Stok' },
      { nama: 'Garam, merica', jumlah: 'secukupnya', kategori: 'Bumbu' },
      { nama: 'Minyak goreng', jumlah: '2 sdm', kategori: 'Stok' },
    ],
    langkah: [
      'Iris bawang merah, bawang putih, dan cabai',
      'Panaskan minyak, tumis bumbu iris hingga harum',
      'Masukkan telur, orak-arik',
      'Masukkan nasi dingin, aduk rata dengan api besar',
      'Tambahkan kecap manis, garam, merica. Aduk hingga rata.',
    ],
    tipsPrep: 'Pakai nasi sisa kemarin (nasi dingin lebih bagus untuk nasi goreng). Bumbu iris bisa diprep.',
    tahanSimpan: 'Langsung dimakan. Tidak cocok untuk meal prep.',
    isFavorite: false,
  },
  {
    name: 'Rendang Daging',
    emoji: '🥩',
    category: 'Protein',
    waktuMasak: 120,
    level: 'Sulit',
    porsi: 8,
    bahan: [
      { nama: 'Daging sapi', jumlah: '1 kg, potong dadu', kategori: 'Protein' },
      { nama: 'Santan', jumlah: '800ml', kategori: 'Stok' },
      { nama: 'Bawang merah', jumlah: '10 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '6 siung', kategori: 'Bumbu' },
      { nama: 'Cabai merah', jumlah: '15 buah', kategori: 'Bumbu' },
      { nama: 'Jahe', jumlah: '3 cm', kategori: 'Bumbu' },
      { nama: 'Lengkuas', jumlah: '5 cm', kategori: 'Bumbu' },
      { nama: 'Serai', jumlah: '3 batang', kategori: 'Bumbu' },
      { nama: 'Daun jeruk', jumlah: '5 lembar', kategori: 'Bumbu' },
      { nama: 'Daun kunyit', jumlah: '2 lembar', kategori: 'Bumbu' },
      { nama: 'Kelapa parut sangrai', jumlah: '100g', kategori: 'Bumbu' },
    ],
    langkah: [
      'Haluskan bawang merah, bawang putih, cabai, dan jahe',
      'Tumis bumbu halus dengan sedikit minyak hingga harum',
      'Masukkan daging, aduk hingga berubah warna',
      'Tuang santan, tambahkan serai, lengkuas, daun jeruk, daun kunyit',
      'Masak dengan api kecil sambil sesekali diaduk (1.5-2 jam)',
      'Tambahkan kelapa sangrai, masak hingga santan mengering dan berminyak',
    ],
    tipsPrep: 'Rendang justru MAKIN ENAK setelah didiamkan. Ideal untuk batch cooking!',
    tahanSimpan: 'Kulkas 7 hari, freezer 1 bulan. Panaskan ulang di wajan.',
    isFavorite: false,
  },
  {
    name: 'Soto Ayam',
    emoji: '🍜',
    category: 'Protein',
    waktuMasak: 60,
    level: 'Sedang',
    porsi: 6,
    bahan: [
      { nama: 'Ayam', jumlah: '1/2 ekor', kategori: 'Protein' },
      { nama: 'Kunyit', jumlah: '5 cm', kategori: 'Bumbu' },
      { nama: 'Bawang merah', jumlah: '6 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '4 siung', kategori: 'Bumbu' },
      { nama: 'Jahe', jumlah: '3 cm', kategori: 'Bumbu' },
      { nama: 'Serai', jumlah: '2 batang', kategori: 'Bumbu' },
      { nama: 'Daun salam', jumlah: '3 lembar', kategori: 'Bumbu' },
      { nama: 'Daun jeruk', jumlah: '3 lembar', kategori: 'Bumbu' },
      { nama: 'Soun', jumlah: '100g', kategori: 'Karbohidrat' },
      { nama: 'Tauge', jumlah: '100g', kategori: 'Sayur' },
      { nama: 'Telur rebus', jumlah: '3 butir', kategori: 'Protein' },
      { nama: 'Bawang goreng, seledri, jeruk nipis', jumlah: 'untuk topping', kategori: 'Bumbu' },
    ],
    langkah: [
      'Rebus ayam hingga matang, angkat, suwir-suwir. Simpan kaldunya.',
      'Haluskan kunyit, bawang merah, bawang putih, jahe',
      'Tumis bumbu halus hingga harum, masukkan ke kaldu',
      'Tambahkan serai, daun salam, daun jeruk. Masak 15 menit.',
      'Sajikan: soun, tauge, ayam suwir, telur, siram kuah. Tabur bawang goreng dan seledri.',
    ],
    tipsPrep: 'Kuah bisa dimasak banyak dan disimpan terpisah dari topping. Panaskan kuah saat mau makan.',
    tahanSimpan: 'Kuah: kulkas 4 hari, freezer 2 minggu. Topping: siapkan segar.',
    isFavorite: false,
  },
  {
    name: 'Capcay Sayur',
    emoji: '🥦',
    category: 'Sayur',
    waktuMasak: 20,
    level: 'Mudah',
    porsi: 3,
    bahan: [
      { nama: 'Wortel', jumlah: '1 buah', kategori: 'Sayur' },
      { nama: 'Brokoli', jumlah: '1/2 buah', kategori: 'Sayur' },
      { nama: 'Baby corn', jumlah: '100g', kategori: 'Sayur' },
      { nama: 'Sawi putih', jumlah: '3 lembar', kategori: 'Sayur' },
      { nama: 'Bawang putih', jumlah: '4 siung', kategori: 'Bumbu' },
      { nama: 'Saus tiram', jumlah: '2 sdm', kategori: 'Stok' },
      { nama: 'Maizena', jumlah: '1 sdm + air', kategori: 'Stok' },
      { nama: 'Garam, merica, gula', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Potong semua sayuran sesuai selera',
      'Tumis bawang putih iris hingga harum',
      'Masukkan wortel dulu (paling keras), tumis 2 menit',
      'Tambahkan brokoli, baby corn, sawi putih',
      'Tambahkan saus tiram, garam, merica, gula, sedikit air',
      'Kentalkan dengan larutan maizena, aduk rata, angkat',
    ],
    tipsPrep: 'Sayuran bisa dipotong dan di-blanch sehari sebelumnya. Simpan di wadah tertutup.',
    tahanSimpan: 'Kulkas 2 hari. Reheat di wajan, jangan microwave (jadi lembek).',
    isFavorite: false,
  },
  {
    name: 'Perkedel Kentang',
    emoji: '🥔',
    category: 'Pendamping',
    waktuMasak: 35,
    level: 'Sedang',
    porsi: 10,
    bahan: [
      { nama: 'Kentang', jumlah: '500g', kategori: 'Sayur' },
      { nama: 'Telur', jumlah: '2 butir', kategori: 'Protein' },
      { nama: 'Bawang merah goreng', jumlah: '3 sdm', kategori: 'Bumbu' },
      { nama: 'Daun bawang', jumlah: '2 batang', kategori: 'Bumbu' },
      { nama: 'Garam, merica, pala', jumlah: 'secukupnya', kategori: 'Bumbu' },
      { nama: 'Minyak goreng', jumlah: 'secukupnya', kategori: 'Stok' },
    ],
    langkah: [
      'Rebus kentang hingga empuk, haluskan',
      'Campurkan kentang halus dengan bawang merah goreng, daun bawang iris, garam, merica, pala',
      'Bentuk bulat pipih',
      'Celupkan ke telur kocok',
      'Goreng hingga kuning keemasan',
    ],
    tipsPrep: 'Bentuk perkedel bisa disiapkan dan disimpan di freezer. Goreng langsung dari frozen.',
    tahanSimpan: 'Kulkas 3 hari, freezer 1 bulan (sebelum digoreng)',
    isFavorite: false,
  },
  {
    name: 'Sambal Goreng Kentang Ati',
    emoji: '🫕',
    category: 'Pendamping',
    waktuMasak: 40,
    level: 'Sedang',
    porsi: 6,
    bahan: [
      { nama: 'Kentang', jumlah: '300g, potong dadu', kategori: 'Sayur' },
      { nama: 'Ati ampela ayam', jumlah: '250g', kategori: 'Protein' },
      { nama: 'Cabai merah', jumlah: '10 buah', kategori: 'Bumbu' },
      { nama: 'Bawang merah', jumlah: '6 butir', kategori: 'Bumbu' },
      { nama: 'Bawang putih', jumlah: '3 siung', kategori: 'Bumbu' },
      { nama: 'Santan', jumlah: '200ml', kategori: 'Stok' },
      { nama: 'Daun salam, lengkuas', jumlah: 'secukupnya', kategori: 'Bumbu' },
      { nama: 'Gula, garam', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Goreng kentang hingga kuning, tiriskan',
      'Rebus ati ampela, potong-potong',
      'Haluskan cabai, bawang merah, bawang putih',
      'Tumis bumbu halus dengan daun salam dan lengkuas',
      'Masukkan santan, masak hingga mengental',
      'Masukkan kentang goreng dan ati ampela, aduk rata',
    ],
    tipsPrep: 'Kentang bisa digoreng dan ati bisa direbus sehari sebelumnya.',
    tahanSimpan: 'Kulkas 3-4 hari',
    isFavorite: false,
  },
  {
    name: 'Mie Goreng Sederhana',
    emoji: '🍝',
    category: 'Karbohidrat',
    waktuMasak: 15,
    level: 'Mudah',
    porsi: 2,
    bahan: [
      { nama: 'Mie telur', jumlah: '2 bungkus', kategori: 'Karbohidrat' },
      { nama: 'Telur', jumlah: '2 butir', kategori: 'Protein' },
      { nama: 'Sawi hijau', jumlah: '2 batang', kategori: 'Sayur' },
      { nama: 'Bawang putih', jumlah: '3 siung', kategori: 'Bumbu' },
      { nama: 'Kecap manis', jumlah: '2 sdm', kategori: 'Stok' },
      { nama: 'Saus tiram', jumlah: '1 sdm', kategori: 'Stok' },
      { nama: 'Garam, merica', jumlah: 'secukupnya', kategori: 'Bumbu' },
    ],
    langkah: [
      'Rebus mie hingga al dente, tiriskan',
      'Tumis bawang putih iris hingga harum',
      'Masukkan telur, orak-arik',
      'Masukkan sawi, tumis sebentar',
      'Masukkan mie, kecap manis, saus tiram, garam, merica',
      'Aduk rata dengan api besar, angkat',
    ],
    tipsPrep: 'Mie bisa direbus dan ditiriskan sebelumnya. Beri sedikit minyak agar tidak lengket.',
    tahanSimpan: 'Langsung dimakan.',
    isFavorite: false,
  },
]

export async function seedDatabase() {
  const count = await db.recipes.count()
  if (count === 0) {
    await db.recipes.bulkAdd(seedRecipes)
    console.log(`Seeded ${seedRecipes.length} recipes`)
  }
}
